name: patrick
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - transformers
  - datasets 
  - numpy
  - selenium
  - webdriver-manager
  - pandas
  - tqdm
  - pip
  - jupyter
  - ipykernel
  - pytorch #=2.0 #::pytorch-nightly
  - pytorch-cuda=11.7 #::nvidia
  - wandb
  - tqdm
  - pip:
    - tiktoken