name: patrick
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch-nightly
dependencies:
  - python
  - transformers
  - datasets 
  - numpy
  - selenium
  - webdriver-manager
  - pandas
  - tqdm
  - pip
  - jupyter
  - ipykernel
  - pytorch
  - pytorch-cuda=11.8
  - wandb
  - tqdm
  - pip:
    - tiktoken